import Head from "next/head";
import Image from "next/image";
import ColorPalette from "~/components/ColorPalette";
import FibonacciView, {
  OrientationEnum,
} from "~/components/FibonacciGrid/FibonacciView";
import Opepen from "~/components/Opepen";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="main flexColCenter gap-20">
        {/* <div className="flexRow items-center justify-around min-w-full">
          <h1 className=" text-3xl">Opepen</h1>
          <ColorPalette />
        </div>

        <Opepen /> */}
        <div className="flexRowCenter gap-8">
          <div className="flexColCenter">
            <h1>Horizontal</h1>
            <FibonacciView _orientation={OrientationEnum.horizontal}>
              <Image
                height={480}
                width={360}
                style={{ width: "100%", height: "100%" }}
                alt="Upsplash"
                src="/upsplash/vertical_1.jpg"
              />
              <Image
                height={480}
                width={360}
                style={{ width: "100%", height: "100%" }}
                alt="Upsplash"
                src="/upsplash/vertical_2.jpg"
              />
              <Image
                height={480}
                width={360}
                style={{ width: "100%", height: "100%" }}
                alt="Upsplash"
                src="/upsplash/horizontal_3.jpg"
              />
            </FibonacciView>
          </div>
          <div className="flexColCenter">
            <h1>HorizontalReverse</h1>
            <FibonacciView _orientation={OrientationEnum.horizontalReverse}>
              <Image
                height={480}
                width={360}
                alt="Upsplash"
                style={{ width: "100%", height: "100%" }}
                src="/upsplash/vertical_6.jpg"
              />
              <Image
                height={480}
                width={360}
                alt="Upsplash"
                style={{ width: "100%", height: "100%" }}
                src="/upsplash/vertical_5.jpg"
              />
              <Image
                height={480}
                width={360}
                alt="Upsplash"
                style={{ width: "100%", height: "100%" }}
                src="/upsplash/horizontal_6.jpg"
              />
            </FibonacciView>
          </div>
          <div className="flexColCenter">
            <h1>Vertical</h1>
            <FibonacciView _orientation={OrientationEnum.vertical}>
              <Image
                height={360}
                width={480}
                alt="Upsplash"
                style={{ width: "100%", height: "100%" }}
                src="/upsplash/horizontal_2.jpg"
              />
              <Image
                height={360}
                width={480}
                alt="Upsplash"
                style={{ width: "100%", height: "100%" }}
                src="/upsplash/horizontal_4.jpg"
              />
              <Image
                height={360}
                width={480}
                alt="Upsplash"
                style={{ width: "100%", height: "100%" }}
                src="/upsplash/horizontal_5.jpg"
              />
            </FibonacciView>
          </div>
          <div className="flexColCenter">
            <h1>VerticalReverse</h1>
            <FibonacciView _orientation={OrientationEnum.verticalReverse}>
              <Image
                height={360}
                width={480}
                alt="Upsplash"
                style={{ width: "100%", height: "100%" }}
                src="/upsplash/horizontal_8.jpg"
              />
              <Image
                height={360}
                width={480}
                alt="Upsplash"
                style={{ width: "100%", height: "100%" }}
                src="/upsplash/horizontal_7.jpg"
              />
              <Image
                height={360}
                width={480}
                alt="Upsplash"
                style={{ width: "100%", height: "100%" }}
                src="/upsplash/vertical_3.jpg"
              />
            </FibonacciView>
          </div>
        </div>
      </div>
    </>
  );
}
