import Head from "next/head";
import ColorPalette from "~/components/ColorPalette";
import FibonacciView, { OrientationEnum } from "~/components/FibonacciGrid/FibonacciView";
import Opepen from "~/components/Opepen";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="main flexColCenter gap-20">
        {/* <div className="flexRow items-center justify-around min-w-full">
          <h1 className=" text-3xl">Opepen</h1>
          <ColorPalette />
        </div>

        <Opepen /> */}
        <FibonacciView
        _orientation={OrientationEnum.horizontal}/>
                <FibonacciView
        _orientation={OrientationEnum.horizontalReverse}/>
                <FibonacciView
        _orientation={OrientationEnum.vertical}/>
                <FibonacciView
        _orientation={OrientationEnum.verticalReverse}/>
      </div>
    </>
  );
}
